### PR TITLE
Fix spacing

### PR DESCRIPTION
**Pull request by jacktuck**
Before
Before

After
After

### CODE REVIEW

**Comment by jacktuck** [comment]
@jaebradley Any thoughts?

**Comment by Gatix** [comment]
It's better to put the margin in the parent container

```diff
#atomify {
  display: inline-block;
+  margin-left: 1em;
}
```

**Comment by jacktuck** [comment]
@Gatix But there are two images, default is margin right of 10px.

**Comment by Gatix** [comment]
Yes. Because if you remove the margin on the left, then it will be clipping the marquee

image

**Comment by jacktuck** [comment]
That's what #29 is for

**Comment by jaebradley** [comment]
@jacktuck IMHO `1.5em` maybe looks like *too* much spacing?

### 1.5em
image

### 0.5em
image

**Comment by jaebradley** [comment]
@jacktuck the previous comment and commit was my fault - I didn't see you delete the `margin-right`. With only the `margin-left: 1.5em` it looks pretty good.

image

**Pull request merged**
